<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<script>
  /*
  * Promise.all()
  * */
  //Promise.all方法用于将多个 Promise 实例，包装成一个新的 Promise 实例。
  //const p = Promise.all([p1, p2, p3])

  /*上面代码中，Promise.all方法接受一个数组作为参数，p1、p2、p3都是 Promise 实例，如果不是，就会先调用下面讲到的Promise.resolve方法，将参数转为 Promise 实例，再进一步处理。（Promise.all方法的参数可以不是数组，但必须具有 Iterator 接口，且返回的每个成员都是 Promise 实例。）

  p的状态由p1、p2、p3决定，分成两种情况。

  （1）只有p1、p2、p3的状态都变成fulfilled，p的状态才会变成fulfilled，此时p1、p2、p3的返回值组成一个数组，传递给p的回调函数。

  （2）只要p1、p2、p3之中有一个被rejected，p的状态就变成rejected，此时第一个被reject的实例的返回值，会传递给p的回调函数。

  下面是一个具体的例子。*/
  let getJSON = function (url) {
    let promise3 = new Promise(function(resolve, reject){
      let handler3 = function () {
        if(this.readyState !== 4){
          return
        }
        if(this.status === 200 && this.response.recode === 0){
          resolve(this.response)
        }else{
          //reject(new Error(this.statusText))
          reject('hahahaha')
        }
      }
      let client3 = new XMLHttpRequest()
      client3.open('GET', url)
      client3.onreadystatechange = handler3
      client3.responseType = 'json'
      client3.setRequestHeader('Accept', 'application/json')
      client3.send()
    })
    return promise3
  }

  let promises = ['http://das.51youpu.com/das/paper/manage/listCommon?system=YOUPU&sid=fa725e0c-7412-416d-8c91-b0684931e7fc&uid=1065722645&currentPage=1&pageSize=10&schoolId=63&roleId=10&phaseYear=0&subjectCode=0&semester=0', 'http://das.51youpu.com/das/paper/manage/getSelectCondition?system=YOUPU&sid=fa725e0c-7412-416d-8c91-b0684931e7fc&uid=1065722645&roleId=10&schoolId=63', 'http://das.51youpu.com/das/testManager/getSchoolInfoByUid?system=YOUPU&sid=fa725e0c-7412-416d-8c91-b0684931e7fc&uid=1065722645'].map(function (url) {
    return getJSON(url)
  })
  Promise.all(promises).then(function (data) {
    console.log(data)
  }).catch(function (reason) {
    console.log(reason);
  })

  /*注意，如果作为参数的 Promise 实例，自己定义了catch方法，那么它一旦被rejected，并不会触发Promise.all()的catch方法。*/

  let p1 = new Promise((resolve, reject) => {
    resolve('hello')
  })
    .then(result => result)
    .catch(e => e)

  let p2 = new Promise((resolve, reject) => {
    throw new Error('报错了！')
  })
    .then(result => result)
    .catch(e => e)

  Promise.all([p1, p2]).then(result => console.log(result)).catch(e => console.log(e))

  /*上面代码中，p1会resolved，p2首先会rejected，但是p2有自己的catch方法，该方法返回的是一个新的 Promise 实例，p2指向的实际上是这个实例。该实例执行完catch方法后，也会变成resolved，导致Promise.all()方法参数里面的两个实例都会resolved，因此会调用then方法指定的回调函数，而不会调用catch方法指定的回调函数。

  如果p2没有自己的catch方法，就会调用Promise.all()的catch方法。*/

  let p3 = new Promise((resolve, reject) => {
    resolve('hello')
  })
    .then(result => result)
    .catch(e => e)

  let p4 = new Promise((resolve, reject) => {
    throw new Error('报错了！')
  })
    .then(result => result)

  Promise.all([p3, p4]).then(result => console.log(result)).catch(e => console.log(e))
</script>
</body>
</html>